name: mongo-sharding

services:
  configsvr:
    image: mongo:latest
    container_name: configsvr
    command: ["mongod", "--configsvr", "--replSet", "configReplSet", "--port", "27017"]
    ports:
      - "27017:27017"
    volumes:
      - config_data:/data/db

  shard1:
    image: mongo:latest
    container_name: shard1
    command: ["mongod", "--shardsvr", "--replSet", "shard1ReplSet", "--port", "27018"]
    ports:
      - "27018:27018"
    volumes:
      - shard1_data:/data/db

  shard2:
    image: mongo:latest
    container_name: shard2
    command: ["mongod", "--shardsvr", "--replSet", "shard2ReplSet", "--port", "27019"]
    ports:
      - "27019:27019"
    volumes:
      - shard2_data:/data/db

  mongos:
    image: mongo:latest
    container_name: mongos
    command: ["mongos", "--configdb", "configReplSet/configsvr:27017", "--port", "27020"]
    ports:
      - "27020:27020"
    depends_on:
      - configsvr
      - shard1
      - shard2

volumes:
  config_data:
  shard1_data:
  shard2_data:
