name: mongo-sharding

services:
  pymongo_api:
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      mongos_router:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos_router"
      MONGODB_DATABASE_NAME: "somedb"

  configSrv:
    image: mongo:6.0
    container_name: configSrv
    restart: always
    ports:
      - "27019:27019"
    volumes:
      - config-data:/data/db
    command: [ "--configsvr", "--replSet", "config_server", "--bind_ip_all", "--port", "27019" ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27019", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  shard1-db1:
    image: mongo:6.0
    container_name: shard1-db1
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - shard1-db1-data:/data/db
    command: [ "--shardsvr", "--replSet", "shard1", "--bind_ip_all", "--port", "27017" ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27017", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard2-db1:
    image: mongo:6.0
    container_name: shard2-db1
    restart: always
    ports:
      - "27018:27018"
    volumes:
      - shard2-db1-data:/data/db
    command: [ "--shardsvr", "--replSet", "shard2", "--bind_ip_all", "--port", "27018" ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27018", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  mongos_router:
    image: mongo:6.0
    container_name: mongos_router
    restart: always
    ports:
      - "27020:27020"
    command: [ "mongos", "--configdb", "config_server/configSrv:27019", "--bind_ip_all", "--port", "27020" ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27020", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

volumes:
  config-data:
  shard1-db1-data:
  shard2-db1-data:
