services:
  # Config server
  configsvr:
    container_name: configsvr
    hostname: configsvr
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --configsvr --replSet configReplSet --port 27019
    volumes:
      - configsvr_data:/data/db
    ports:
      - "27019:27019"

  # Shard 1
  shard1:
    container_name: shard1
    hostname: shard1
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard1ReplSet --port 27018
    volumes:
      - shard1_data:/data/db
    ports:
      - "27018:27018"

  # Shard 2
  shard2:
    container_name: shard2
    hostname: shard2
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard2ReplSet --port 27017
    volumes:
      - shard2_data:/data/db
    ports:
      - "27017:27017"

  # Router
  mongoshard:
    container_name: mongoshard
    hostname: mongoshard
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongos --configdb configReplSet/configsvr:27019 --port 27016 --bind_ip_all
    depends_on:
      - configsvr
      - shard1
      - shard2
    ports:
      - "27016:27016"

  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - mongoshard
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongoshard:27016"
      MONGODB_DATABASE_NAME: "somedb"

volumes:
  configsvr_data:
  shard1_data:
  shard2_data: