name: mongo-sharding-repl
version: '3'
services:
  configSrv:
    image: mongo:latest
    container_name: configSrv
    restart: always
    volumes:
      - ./scripts:/scripts
      - config-data:/data/db
    command: mongod --port 27017 --configsvr --replSet config_server

  shard1_1:
    image: mongo:latest
    container_name: shard1_1
    restart: always
    volumes:
      - ./scripts:/scripts
      - shard1_1-data:/data/db
    command: mongod --port 27017 --shardsvr --replSet shard1
    links:
      - shard1_2
      - shard1_3

  shard1_2:
    image: mongo:latest
    container_name: shard1_2
    restart: always
    volumes:
      - ./scripts:/scripts
      - shard1_2-data:/data/db
    command: mongod --port 27017 --shardsvr --replSet shard1

  shard1_3:
    image: mongo:latest
    container_name: shard1_3
    restart: always
    volumes:
      - ./scripts:/scripts
      - shard1_3-data:/data/db
    command: mongod --port 27017 --shardsvr --replSet shard1

  shard2_1:
    image: mongo:latest
    container_name: shard2_1
    restart: always
    volumes:
      - ./scripts:/scripts
      - shard2_1-data:/data/db
    command: mongod --port 27017 --shardsvr --replSet shard2
    links:
      - shard2_2
      - shard2_3

  shard2_2:
    image: mongo:latest
    container_name: shard2_2
    restart: always
    volumes:
      - ./scripts:/scripts
      - shard2_2-data:/data/db
    command: mongod --port 27017 --shardsvr --replSet shard2

  shard2_3:
    image: mongo:latest
    container_name: shard2_3
    restart: always
    volumes:
      - ./scripts:/scripts
      - shard2_3-data:/data/db
    command: mongod --port 27017 --shardsvr --replSet shard2

  mongos_router:
    image: mongo:latest
    container_name: mongos_router
    restart: always
    ports:
      - "27020:27020"
    command: mongos --port 27020 --configdb config_server/configSrv:27017 --bind_ip_all
    volumes:
      - ./scripts:/scripts
      - router-data:/data/db

  pymongo_api:
    container_name: pymongo_api
    build:
      context: ./../api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - mongos_router
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos_router:27020"
      MONGODB_DATABASE_NAME: "somedb"

volumes:
  config-data:
  shard1_1-data:
  shard1_2-data:
  shard1_3-data:
  shard2_1-data:
  shard2_2-data:
  shard2_3-data:
  router-data:
