services:
  shard1:
    container_name: shard1
    image: dh-mirror.gitverse.ru/mongo:latest
    volumes:
      - shard1_data_container:/data/db

  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - shard1
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://shard1"
      MONGODB_DATABASE_NAME: "somedb"


volumes:
  shard1_data_container: